services:
  web:
    image: ghcr.io/shepherd-itsec/adventurebord:latest
    container_name: flask_web
    volumes:
      # mount config.json so hosts can customize without rebuilding
      - ./config/config.json:/app/config/config.json:ro
      - static_data:/app/static
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: flask_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # directly mount static files to nginx so it host them faster
      - static_data:/app/static:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - web
    restart: always

volumes:
  db_data:
  static_data: