services:
  web:
    build: .
    container_name: flask_web
    volumes:
      # mount config.dev.json so hosts can customize without rebuilding
      - ./app/config/config.dev.json:/app/app/config/config.json:ro
      - static_data:/app/app/static
    expose:
      - "5000"
    environment:
      - FLASK_ENV=development
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: flask_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # directly mount static files to nginx so it host them faster
      - static_data:/app/app/static:ro
      - ../nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../certs:/etc/nginx/certs:ro
    depends_on:
      - web
    restart: always

volumes:
  db_data:
  static_data: